spring: 
  profiles:
    active: dev
     
---

spring: 
  application:
    name: microservicecloud-config-atguigu-dev
  profiles: dev #开发环境
  
  ---

spring: 
  application:
    name: microservicecloud-config-atguigu-test
  profiles: test #测试环境